sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5tFix2QkeUuXDYd9SA3J
    access-key-secret: dx2bAI4cG770k19guhq27xlm7acUjJ
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-paibumeng
